### ISSUE TITLE
Inconsistent file format of images for remote datasets

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/remote-datasets#104]
After PR #101 there are now both PNG and JPG files stored in the folder at https://github.com/GenericMappingTools/remote-datasets/tree/main/docs/_static for the `GMT_earth_age` and the `GMT_earth_mask` remote dataset images. For the thumbnail images on the overview page, the JPG files are used, but for the large images on the separate documentation pages, the PNG files are used. For `GMT_earth_mask` the PNG and JPG files are not identical (please compare https://www.generic-mapping-tools.org/remote-datasets/ and https://www.generic-mapping-tools.org/remote-datasets/earth-mask.html). 
Maybe it makes sense to consistently use one format, i.e., the JPG format, across all remote datasets and delete the PNG files?

**Comment by Esteban82** [comment]
Well here there are two issues.


### 1. Two types of images (jpg and png)

The idea of both types is that I checked (when I did #95) both types of images and I choose the smaller one (based of size). 

For example, you can see that GMT_earth_mask.jpg is 53,7 KiB and GMT_earth_mask.png is 36,9 KiB. And the whole idea of the thumbnails was to reduce the sizes of the files.

### 2. Images without use
Yes, I think that we should delete those files.

**Comment by seisman** [comment]
> Maybe it makes sense to consistently use one format, i.e., the JPG format, across all remote datasets and delete the PNG files?

I agree with @yvonnefroehlich that using a single format can make the maintainance much easier.

**Comment by Esteban82** [comment]
> For `GMT_earth_mask` the PNG and JPG files are not identical (please compare https://www.generic-mapping-tools.org/remote-datasets/ and https://www.generic-mapping-tools.org/remote-datasets/earth-mask.html).

What version should I use? The old one or teh new one?
