### ISSUE TITLE
What to do if a full global set is needed

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/remote-datasets#107]
For many purposes it would be nice to somehow get, say,` earth_relief_15s.grd` downloaded in one piece instead of having GMT reassemble all the tiles.  It is particularly useful if one is running animations and needs a global grid. Unless it is 6m and up we have to run **grdcut** to assemble the higher dimension global file (which we made during the processing).

Once option to implement this would be to simply distinguish between `@earth_relief_15s`[`_p|g`] and `@earth_relief_15s`[`_p|g`]`.grd`, the latter requesting the whole enchilada.  These would then have to be uploaded, of course, and placed in the _gmt_data_server.txt_ in a similar way to the lower wool-earth grids.

Negative is this duplicates memory requirements for the biggest data sets.  Any thoughts?

**Comment by Esteban82** [comment]
With such large files, isn't it likely that a crash will occur and the download will be interrupted?

Is it completely out of the question to download all the tiles from GMT and assemble them on the local pc?

**Comment by PaulWessel** [comment]
Well,` gmt grdcut @earth_relief_15m -Rd -Gearth_relief_15s.grd `does that, but having N jobs calling curl is more likely to fail than 1 job.  I just made a JP@ file of the entire earth_relief_15s_p.grd and the resulting file is about the same as the sum of all the individual tiles, i.e., half the size of the netcdf grid.  So the recipe would be the same as for tiles: Download the jp2 file and convert to netcdf locally.

**Comment by Esteban82** [comment]
I think that I would prefer to use that command in the `pre.sh` scripts as in the example of animation 9 where the intensity grid was created first.

```
cat << 'EOF' > pre.sh
#!/usr/bin/env bash
# Pre-script: Runs once to produce files needed for all frames
gmt begin
	gmt grdgradient @earth_relief_30s -A90 -Nt2.5 -Gearth_relief_30s+2.5_int.nc
	gmt makecpt -Cgeo -H > MOR_topo.cpt
gmt end
EOF
```

**Comment by PaulWessel** [comment]
That animation should be updated to run the **grdcut** in the pre so we have the full global grid to be used in main.sh

**Comment by Esteban82** [comment]
> That animation should be updated to run the **grdcut** in the pre so we have the full global grid to be used in main.sh

Yes, I was thinking the same. 


In some cases, maybe NOT all the tiles are needed and it would good to have a way to knowing exactly which tiles are going to be needed for the animation.

**Comment by PaulWessel** [comment]
Potentially, in this animation it could be all.

**Comment by seisman** [comment]
@Esteban82 can this issue be closed?

**Comment by Esteban82** [comment]
Yes, I think so.
