### ISSUE TITLE
Create a docs page with all remote files

### ISSUE THREAD

**Issue by leouieda** [GenericMappingTools/remote-datasets#12]
**Description of the desired feature**

Currently, there is no page that lists all remote files, what they are, where they come from, and what they contain. We should have such a page. Bonus points if there are plots these files as well.

**Comment by meghanrjones** [comment]
I moved this over to the remote-datasets repository since it would be a good place for the page.

**Comment by Esteban82** [comment]
I think that this can be close. The doc page already exists.
