### ISSUE TITLE
New dataset announcements on the forum, twitter, and instagram

### ISSUE THREAD

**Issue by meghanrjones** [GenericMappingTools/remote-datasets#18]
This issue is for tracking progress on the announcements of the new datasets.

- [x] Create animation or image showing off new datasets
- [x] Publish Forum announcement
- [x] Post on twitter
- [x] Post on instagram
- [x] Post on website news section

**Comment by Esteban82** [comment]
I think that an image is better for instagram and twitter. I think we should do an image like the [last post on twitter](https://pbs.twimg.com/media/FG1FMCnWUAAD9jD?format=jpg&name=small) (i.e. like a poster) with global maps from the the new/all remote data sets available.

**Comment by PaulWessel** [comment]
Here is an option; you can change from 30m to 06m once happy with layout:

```
#!/bin/bash
cat << EOF > /tmp/t.lis
-180	90	TL	0	relief
0	90	TC	1	age
180	90	TR	2	gebco
-180 	35	ML	3	geoid
0	35	MC	4	faa
180	35	MR	5	vgg
-180 	0	ML	6	day
180 	0	MR	8	night
-180 	-35	ML	9	mag
0	-35	MC	10	mag4km
180	-35	MR	11	wdmam
-180	-90	BL	12	synbath
0	-90	BC	13	mask
180	-90	BR	14	gebcosi
EOF

gmt begin all_data png
	gmt subplot begin 5x3 -Rd -JQ14c -M0p -B0 -Fs14c/7c
		while read x y just pos name; do
			gmt grdimage @earth_${name}_30m -c${pos}
		done < /tmp/t.lis
		awk '{printf "%s %s %s %s\n", $1, $2, $3, $5}' /tmp/t.lis | gmt text -F+f24p,Helvetica-Bold+j -Dj14p -Bx0g120+60 -By0g36+18 -c7
	gmt subplot end
gmt end show
```

**Comment by PaulWessel** [comment]
here is a crack at an announcement text:

We are pleased to announce a significant upgrade to the remote data sets that are easily accessible from GMT via the "@" remote file prefix.  In addition to refreshing the earth_relief collection to the latest 2.3 SRTM+ release, we also add the synbath version (adds modeling to improve bathymetry predictions for young abyssal hills and small seamounts).  Two additional relief grids are also included: Gebco and its sub-ice (gebcosi) variant.  Several geopotential grids have been included this time, such as the EGM2008 geoid and Sandwell/Smith versions of free-air anomalies and vertical gravity gradients.  We also added the sea surface and 4-km-altitude EMAG2 anomalies from USGS and the magnetic anomalies represented by WDMAM. WIth previously released datasets for crustal ages, land/sea masks, and day and night imagery we now offer 14 remote grids.  These are all on display in the graph above; read more about then on the GMT remote data set web page [url].

Maybe @meghanrjones can make this readable and use it  for the news item, forum announcement, and twitter, and after that perhaps @Esteban82 can use it for Instagram?

**Comment by meghanrjones** [comment]
Yes, I can polish it up. To clarify, do you want me to post on the forum or just share the revision back here?

**Comment by PaulWessel** [comment]
Cut out the middle-man and just post once you are happy with the text!

**Comment by meghanrjones** [comment]
I posted the forum announcement at https://forum.generic-mapping-tools.org/t/gmt-remote-dataset-upgrades/2627, but was not able to post the image due to the most compressed file size (1.7 MB) being larger than Discourse would allow. I will include the image on the twitter announcement.

**Comment by PaulWessel** [comment]
Nice news item!  I think it is OK with no pix there since you have links to the real things.

**Comment by meghanrjones** [comment]
Website addition is at https://github.com/GenericMappingTools/website/pull/129 and twitter post is at https://twitter.com/gmt_dev/status/1493343171601915908.

**Comment by meghanrjones** [comment]
> Just post on [Instagram](https://www.instagram.com/p/CaFJFieLJ2y/).

Looks great, thanks!
