### ISSUE TITLE
Switch from sphinx-panels to sphinx-design

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/remote-datasets#23]
In PR #16, the sphinx-panels extension is used to improve the landing page, but the sphinx-panels extension will be deprecated and be replaced by [sphinx-design](https://github.com/executablebooks/sphinx-design#comparison-to-sphinx-panels) (https://github.com/executablebooks/sphinx-panels/issues/67). 

The syntax of the sphinx-design extension is also easier to read and understand. We should migrate sphinx-panels to sphinx-design.

I'd like to help with the migration if agreed.

**Comment by meghanrjones** [comment]
Looks nice - sounds fine to me.
