### ISSUE TITLE
SRTM15+V2.4 released

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#33]
Since march 6th there is a new version (2.4) of SRTM15+ (@earth_relief). 
https://topex.ucsd.edu/pub/srtm15_plus/

**Comment by meghanrjones** [comment]
If you are interested in testing out the new V2.4 files, you can compile GMT with `set (GMT_DATA_SERVER "test")` in your `ConfigUserAdvanced.cmake`, which was added in https://github.com/GenericMappingTools/gmt/pull/6147 (xref https://github.com/GenericMappingTools/gmtserver-admin/pull/144, https://github.com/GenericMappingTools/gmtserver-admin/issues/147). We could move the updated datasets over to oceania any time and update the docs, but it would be nice to address https://github.com/GenericMappingTools/gmt/issues/6422 first.
