### ISSUE TITLE
Explain the data values in earth_mask grids

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/remote-datasets#37]
https://www.generic-mapping-tools.org/remote-datasets/earth-masks.html

![image](https://user-images.githubusercontent.com/3974108/168960081-13b96ddb-aee4-42d7-8e7e-a8fd57fbee6f.png)

The documentation for earth-mask does not explain what the values mean in the earth-mask grids, although I can guess that 0 means ocean and 1 means land from the legend of the top figure.

I think we should:

- Clearly explain the meaning of the values 0-4
- Give the command that is used to generate the earth_mask grids (e.g., `grdlandmask -N0/1/2/3/4`)

**Comment by PaulWessel** [comment]
It certainly can be improved.  We have information about levels in **coast** and **gshhg** modules but there we talk about the levels of the lines.  Here we are talking about the areas between the levels (or in the case of the ocean, the areas outside level 1 (shoreline).  So a better description might be

0. Ocean areas beyond the shoreline
1. Land areas inside the shoreline
2. Lakes inside the land area
3. Islands in lakes in the land area
4. Smaller lakes in islands that are found in lakes inside the land area

Not many of category 4 but there are at least one - not visible in this plot (neither are category 3 I think unless using full resolution).

I can work on this tomorrow unless you want to use this and put it in the right place.  I think a link to the **coast** and/or **gshhg** documentation is probably also helpful here given the two Antarctica shorelines.

**Comment by PaulWessel** [comment]
Hi @seisman, looking at [this information](https://www.generic-mapping-tools.org/remote-datasets/earth-mask.html#technical-information), isn't it pretty clear anyway?

**Comment by seisman** [comment]
> Hi @seisman, looking at [this information](https://www.generic-mapping-tools.org/remote-datasets/earth-mask.html#technical-information), isn't it pretty clear anyway?

Do you mean this sentence?

> Given that GSHHG contains 5 levels (ocean, land, lake, island-in-lake, pond-in-island-in-lake) corresponding to levels 0-4, the mask grids were computed to reflect those 5 levels. 

When I read this sentence, I know that there are 5 levels 0-4, but I'm still unsure if grid value=0 means level 0. So I feel a description you posted in  https://github.com/GenericMappingTools/remote-datasets/issues/37#issuecomment-1129634117 is better.

**Comment by PaulWessel** [comment]
> I don't see why we are distributing masks that go beyond level 2 (actually I don't understand why we are even distributing mask grids at all that can be computed with a one-liner.)

Please try making a global GSHHG mask at full resolution and watch the clock...
