### ISSUE TITLE
feature request: GEBCO bathymetry and GSHHS coastline

### ISSUE THREAD

**Issue by aragong** [GenericMappingTools/remote-datasets#4]
Hi every body,

I want to focus your attention on these two databases for your consideration. I think that will be very useful to have direct access to them. I share with you the links to the main projects of both of them:
- [GEBCO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/)
- [GSHHS](https://www.soest.hawaii.edu/pwessel/gshhg/)

Indeed I code some workaround, I currently use to extract GSHHS coastline (shpfiles) using gepandas, you can check the feature request I did in [pyGMT ](https://github.com/GenericMappingTools/pygmt/issues/1636). I think these features will be easy to implement and very useful for the community.

Have a nice weekend!

**Comment by meghanrjones** [comment]
@aragong, the GEBCO datasets are now available through GMT's remote file mechanism - https://www.generic-mapping-tools.org/remote-datasets/earth-gebco.html

**Comment by aragong** [comment]
great! The documentation looks nice, I missed a one-line code example like there is in others datasets...
Do you have planned to make this database accessible from PyGMT?

**Comment by meghanrjones** [comment]
Thanks for the suggestion - I opened an issue for adding examples in https://github.com/GenericMappingTools/remote-datasets/issues/25.

Yes, it would be nice to have functions for loading these datasets in PyGMT. I'll open an issue over there with some instructions for how to add the feature since adding support for these datasets would be a 'good first issue'.

**Comment by seisman** [comment]
I think we can close this issue because GEBCO is available now and GSHHG has been a built-in dataset in GMT for a long time. 

The other requests like the PyGMT support and the one-liner examples are tracked in separate issues instead.
