### ISSUE TITLE
Bug in earth_relief_30s_g ?

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#42]
It seems there is an error in the processing of @earth_relief_30s_g.

![earth_relief](https://user-images.githubusercontent.com/17908951/197216652-3d3e8d5b-f94a-4b90-87af-007b88d6c130.png)

```
gmt begin earth_relief png
	gmt grdimage @earth_relief_30s_g -Bf -Cgeo -JM5c -B+t"relief_30s_g" -R-72/-64/-35/-30
	gmt grdimage @earth_relief_30s_p -Bf -Cgeo -X5c -B+t"relief_30s_p"
	gmt grdimage @earth_relief_01m_g -Bf -Cgeo -X5c -B+t"relief_01m_g"
	gmt grdimage @earth_gebco_30s_g -Bf -Cgeo -X5c -B+t"gebco_30s_g"
gmt end

```

**Comment by PaulWessel** [comment]
I also get a blue plot for Gebco.

**Comment by PaulWessel** [comment]
The 30x30s tile that is downloaded for Gebco is definitively just water for me (I removed the entire earth_gebco dir so I got the latest files).  Remind me if it was @PaulWessel , @maxrjones or @Esteban82 who processed these - I just cannot remember as the last months are a blur...

**Comment by Esteban82** [comment]
> 

I deleted my gebco data and now I also get the wrong image. Also the synbath is failing. 

I think @PaulWessel procces the gebco. I tried but I hadn't enough memory on my pc to do it.

**Comment by PaulWessel** [comment]
OK, I see I did get Gebco_2022.nc on my Hawai machine so downloaded again here in Norway.  Will check what could go wrong since the script used for 2022 is the same as for 2021...But we may not know if it worked before.

**Comment by Esteban82** [comment]
I think this was fixed. I run:

`gmt grdimage @earth_relief_30s_g -Bf -Cgeo -JM5c -B+t"relief_30s_g" -R-72/-64/-35/-30 -png lixo`


![lixo](https://github.com/GenericMappingTools/remote-datasets/assets/17908951/192e2ac0-4973-422f-a6ce-7fa9edb92563)
