### ISSUE TITLE
Need to update the scripts/remote_map_check.sh script after adding moon datasets

### ISSUE THREAD

**Issue by seisman** [GenericMappingTools/remote-datasets#59]
Currently, the `scripts/remote_map_check.sh` script only works for earth dataset.

**Comment by Esteban82** [comment]
I have made another script based on that just to test the "planets" reliefs grids. That would be a solution. But we will have 2 scripts to check the datasets.

**Comment by PaulWessel** [comment]
Probably test to have one script per dataset and run on CLI or use Makefile to run all.

**Comment by seisman** [comment]
Sounds good to me. Closing the issue.
