### ISSUE TITLE
Update files sizes for NASA Day/Night Images

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#65]
The file sizes in [this table](https://www.generic-mapping-tools.org/remote-datasets/earth-daynight.html#id1) are wrong. 

For example it says that the size for the 30s image is 935 MB when in fact is 219M (394 M) for the day (nigth) image. And the sizes (based on the info of gmt_data_server.txt) are consirable different for most of the resolutions. 

What should I do?
1. Only use the sizes for day image? 
2. Only use the sizes for night image? 
3. Use both sizes in the same table?
4. Make another table?

**Comment by PaulWessel** [comment]
Was done a long time ago and probably before all the tiler scripts came online.  Probably label as bug and update the numbers.  Unlikely we get new versions soon (but I dont know)

**Comment by Esteban82** [comment]
> Probably label as bug and update the numbers.

Ok, but how? Which option should I use?

> Only use the sizes for day image?
> Only use the sizes for night image?
> Use both sizes in the same table?
> Make another table?

**Comment by PaulWessel** [comment]
If night images are smaller then use day sizes and in table caption say “The file sizes refer to the day images; the night images are smaller”

you could sum up the sizes for day and night separately then do the math and add (~xx% smaller on average)

**Comment by Esteban82** [comment]
Ok. The sizes varies "linearly" with the resolution from 33 % smaller to 44% bigger. So I will write something like:

"The sizes ranges from 33% smaller for the highest resolution up to 44% bigger for the lowest resolution."

**Comment by PaulWessel** [comment]
Close issue?

**Comment by Esteban82** [comment]
No. I will try to do it today or tomorrow.

**Comment by PaulWessel** [comment]
OK. I am working on some script and makefile for this repo - also see my post #49.
