### ISSUE TITLE
Remove annotated frame from the image for the remote dataset "GSHHG Global Earth Mask"

### ISSUE THREAD

**Issue by yvonnefroehlich** [GenericMappingTools/remote-datasets#83]
This is related to the comment at https://github.com/GenericMappingTools/pygmt/pull/2728#issuecomment-1753006337 by @seisman.

Compared to the images of the other remote datasets, the image of the `GSHHG Global Earth Mask` remote dataset has a fancy frame and annotations (please see https://www.generic-mapping-tools.org/remote-datasets/). This does not look well and is inconsistent. Thus it is suggested to update this image with a version without the annotated fancy frame.

**Comment by Esteban82** [comment]
I have some time. 

Should I only delete `-Baf -BWsNe` in `GMT_earthmask.sh`?

**Comment by Esteban82** [comment]
And maybe I could edit the maps of the Crustal Age and geoid and center them at 0 (instead of 180).

**Comment by yvonnefroehlich** [comment]
> I have some time.
> 
> Should I only delete `-Baf -BWsNe` in `GMT_earthmask.sh`?

Yes, I think so.

**Comment by yvonnefroehlich** [comment]
> And maybe I could edit the maps of the Crustal Age and geoid and center them at 0 (instead of 180).

I think this is a good idea, because I feel it's good to have the images consistent for all remote datasets.

**Comment by Esteban82** [comment]
> Yes, I think so.

Ok. let's try. I also updated the png file.

**Comment by yvonnefroehlich** [comment]
I am just wondering, whether we should addionaly move the legend for `Earth mask` inside the image similar to colorbar for `Earth Seafloor Crustal Age`?

**Comment by Esteban82** [comment]
I move it a bit upwards but no as for the `Earth Seafloor Crustal Age`. In this map, the legend is over Antarctica.

**Comment by Esteban82** [comment]
Fix by #85

**Comment by Esteban82** [comment]
> And maybe I could edit the maps of the Crustal Age and geoid and center them at 0 (instead of 180).

@PaulWessel is there a script to make all the others statics images (beside AGE and Earthmask)? Should I make it?

**Comment by PaulWessel** [comment]
Please do, I think those were one liners
