### ISSUE TITLE
Get ready for GMT 6.5 release

### ISSUE THREAD

**Issue by PaulWessel** [GenericMappingTools/remote-datasets#92]
Hi @Esteban82-

Could you give me an update on where we are with

1. The candidate server (I think it is fully populated, no?)
2. Illustrations for each data set to go on the website showing the data
3. Any scripts that still need to be made?

I think we need to make sure that this repo is completed, and then when we actually release GMT 6.5 then we can run

`make server-release`

Which we have ever done (we have dome `make candidate-release`) but have to look out for issues live.n

**Comment by Esteban82** [comment]
> 1. The candidate server (I think it is fully populated, no?)

I think so. I'm going to look carefully tomorrow. I don't know what happened in the end with the earth_mss grid. Currently there is the mss_sio_v32. Are you going to serve that one?


> 2. Illustrations for each data set to go on the website showing the data

Some images are missing.
Are we going to show all of them? Maybe Seisman has something to say.

> 3. Any scripts that still need to be made?

I think that I can handle it (once we decided which data sets are we going to show).

**Comment by Esteban82** [comment]
For the website (https://www.generic-mapping-tools.org/remote-datasets/index.html) I think that we should include 6 more maps (the 5 planets relief and mss).

Also,maybe we could merge some existing datasets on a same page. Like:

- GEBCO and IGPP earth relief.
- EMAG2 and WDMAM
- VGG and FAA .

**Comment by seisman** [comment]
> > 3\. Illustrations for each data set to go on the website showing the data
> 
> Some images are missing. Are we going to show all of them? Maybe Seisman has something to say.

I think so. Maybe we should also produces smallers thumbnails and show the thumbnails on the front page instead of the full-resolution images.

**Comment by PaulWessel** [comment]
I like the thumbnails idea.  We don't want the default view to be a long list of 20 global plots.

**Comment by Esteban82** [comment]
I think that this can be closed.
