### ISSUE TITLE
Use thumbnails for front page (Index.rst)

### ISSUE THREAD

**Issue by Esteban82** [GenericMappingTools/remote-datasets#93]
As it was suggested in #92, we should use thumbnails for the front page ( https://www.generic-mapping-tools.org/remote-datasets/index.html) 

For a two column content, we could use images with 400px wide. 
Should we use three-column instead? 

I think I can make maps without legends/colorbar. We could leave that for each individual page. 

For the images, I am thinking of using the same name and add the "thumbnail" suffix. 

Any comment, idea or suggestion?

**Comment by seisman** [comment]
> Should we use three-column instead?

At least we should try the 3-column layout.

> I think I can make maps without legends/colorbar. We could leave that for each individual page.

I don't think we should make things too complicated. The easiest solution is adding another `gmt psconvert` call in the scripts but use an option like `-E150` to generate images with a 150-dpi resolution (the default is 300-dpi).

> For the images, I am thinking of using the same name and add the "thumbnail" suffix.

Sounds good. Or we can have all thumbnails in the `doc/_static/thumbnails` directory.

**Comment by Esteban82** [comment]
> The easiest solution is adding another `gmt psconvert`

That module expects a `ps` as an input. I try this instead from this [link](https://gist.github.com/bengarrett/a630fba5de1a68c6de6b): 
`gm convert  GMT_earth_${set}.jpg -thumbnail 150x  GMT_earth_${set}_thumbnail.jpg`

**Comment by seisman** [comment]
> > The easiest solution is adding another `gmt psconvert`
> 
> That module expects a `ps` as an input. I try this instead from this [link](https://gist.github.com/bengarrett/a630fba5de1a68c6de6b): `gm convert GMT_earth_${set}.jpg -thumbnail 150x GMT_earth_${set}_thumbnail.jpg`

It doesn't need a PS in modern mode. You can try adding the following line before `gmt end`:
```
gmt psconvert -A -P -E150 -FGMT_age.thumbnail -Tg
```

**Comment by Esteban82** [comment]
> It doesn't need a PS in modern mode. You can try adding the following line before `gmt end`:
> 
> ```
> gmt psconvert -A -P -E150 -FGMT_age.thumbnail -Tg
> ```

Great. Should I use png format? Or can I use jpg? The png are about the same size that the bigger map. The jpg is about 3-4 times smaller.

**Comment by seisman** [comment]
The smaller the better.

**Comment by PaulWessel** [comment]
Maybe place thumbnails in a table with N by 3 or 4 layout and if clicked go to a large view with dataset specific info?

**Comment by joa-quim** [comment]
Agree with the 3 columns. Probably the titles have to be made shorter or use smaller fonts.

**Comment by Esteban82** [comment]
How should I modify these values to get 3 columns?

```
.. grid:: 1 2 2 2
    :gutter: 4 4 3 3
```

This way is ok?
```
.. grid:: 1 2 3 3
    :gutter: 4 4 3 3
```

**Comment by seisman** [comment]
See https://sphinx-design.readthedocs.io/en/latest/grids.html.

`.. grid:: 1 2 3 3` means different numbers of columns for extra-small, small, medium and large screens. `1 2 3 3` sounds good.

**Comment by Esteban82** [comment]
Done by #95 and #96.
